
(**

A comparison on SQL Server data access methods
==============================================

Type providers + Query Expressions 
-----------------------------------------

 F# Query Expressions (aka LINQ 2.0) is lovely and useful technology. It makes writing data access code a pleasant exercise. 
 There are several different implementations available: [SQLProvider][sql] (recent community effort), [SqlDataConnection][linq2sql]/[DbmlFile][dbml] 
 and [SqlEntityConnection][ef]/[EdmxFile][edmx].  
 
 But I would like to point out some reasons you might prefer SqlCommandProvider over those. 
 Take a look at this  [StackOverflow issue][soissue]. There are dozens of similar questions (hundreds if you include C# LINQ which is essential 
 the same issue). 
 
 So, what's a deal? The thing is, you can have perfectly valid F# code that compiles but still fails at run-time because of
 unsupported F#-to-SQL translation semantics. Contrary, SqlCommandProvider offers "What You See Is What You Get" approach. 
 Once F# code involving SqlCommandProvider passes compilation stage you are guaranteed to have valid executable (both F# code and T-SQL). 
 
 Lack of control and opaqueness of F#-to-SQL conversion spells performance problems too.  
 At times developers are really frustrated by ineffective T-SQL code generated by type providers (most of EF users are aware of this issue). 
 Evolution and changes in T-SQL code generated by type provider may present certain problems too. 
 A data access code that is performing well today can become suboptimal tomorrow. 
 SqlCommandProvider gives you direct access to full power of T-SQL scripting including the latest features which are often 
 unavailable in type providers because they target older or different versions of the system. 
 
   [sql]: http://github.com/fsprojects/SQLProvider
   [linq2sql]: http://msdn.microsoft.com/en-us/library/hh361033.aspx
   [dbml]: http://msdn.microsoft.com/en-us/library/hh361039.aspx
   [ef]: http://msdn.microsoft.com/en-us/library/hh361035.aspx
   [edmx]: http://msdn.microsoft.com/en-us/library/hh361038.aspx
   [soissue]: http://stackoverflow.com/questions/21574254/how-do-i-do-a-contains-query-with-f-query-expressions/21584169

[Dapper](https://code.google.com/p/dapper-dot-net/)
-----------------------------------------

[Generating strongly typed DataSets](http://msdn.microsoft.com/en-us/library/wha85tzb.aspx)
-----------------------------------------

*)

