version: 2
updates:
  # Keep GitHub Actions up to date automatically
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
    labels:
      - "enhancement"
    groups:
      github-actions:
        patterns:
          - "*"
