// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("SqlClient.DesignTime")>]
[<assembly: AssemblyProductAttribute("FSharp.Data.SqlClient.DesignTime")>]
[<assembly: AssemblyDescriptionAttribute("SqlClient F# type providers")>]
[<assembly: AssemblyVersionAttribute("3.0.0")>]
[<assembly: AssemblyFileVersionAttribute("3.0.0")>]
[<assembly: InternalsVisibleToAttribute("SqlClient.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SqlClient.DesignTime"
    let [<Literal>] AssemblyProduct = "FSharp.Data.SqlClient.DesignTime"
    let [<Literal>] AssemblyDescription = "SqlClient F# type providers"
    let [<Literal>] AssemblyVersion = "3.0.0"
    let [<Literal>] AssemblyFileVersion = "3.0.0"
    let [<Literal>] InternalsVisibleTo = "SqlClient.Tests"
