// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("MicrosoftSqlClient.DesignTime")>]
[<assembly: AssemblyProductAttribute("FSharp.Data.SqlClient.DesignTime")>]
[<assembly: AssemblyDescriptionAttribute("SqlClient F# type providers")>]
[<assembly: AssemblyVersionAttribute("2.1.3")>]
[<assembly: AssemblyFileVersionAttribute("2.1.3")>]
[<assembly: InternalsVisibleToAttribute("MicrosoftSqlClient.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "MicrosoftSqlClient.DesignTime"
    let [<Literal>] AssemblyProduct = "FSharp.Data.SqlClient.DesignTime"
    let [<Literal>] AssemblyDescription = "SqlClient F# type providers"
    let [<Literal>] AssemblyVersion = "2.1.3"
    let [<Literal>] AssemblyFileVersion = "2.1.3"
    let [<Literal>] InternalsVisibleTo = "MicrosoftSqlClient.Tests"
