// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("SqlClient")>]
[<assembly: AssemblyProductAttribute("FSharp.Data.SqlClient")>]
[<assembly: AssemblyDescriptionAttribute("SqlClient F# type providers")>]
[<assembly: AssemblyVersionAttribute("2.0.50")>]
[<assembly: AssemblyFileVersionAttribute("2.0.50")>]
[<assembly: InternalsVisibleToAttribute("SqlClient.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SqlClient"
    let [<Literal>] AssemblyProduct = "FSharp.Data.SqlClient"
    let [<Literal>] AssemblyDescription = "SqlClient F# type providers"
    let [<Literal>] AssemblyVersion = "2.0.50"
    let [<Literal>] AssemblyFileVersion = "2.0.50"
    let [<Literal>] InternalsVisibleTo = "SqlClient.Tests"
